twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/custom_types.html.twig']
    globals:
        set: '@App\Services\Settings\Set'
when@test:
    twig:
        strict_variables: true
        
