parameters:
  app.admin_email: 'a@a.ru'
  app.admin_name: 'Admin Adminovich'
  code_checker.url: host.docker.internal
  code_checker.port: 2358
  
  upload_directory: '%kernel.project_dir%/public/uploads/images'
