parameters:
  app.admin_email: 'a@a.ru'
  app.admin_name: 'Admin Adminovich'
  app.host: 'http://localhost'
  code_checker.url: '%env(CODE_CHECKER_URL)%'
  code_checker.port: '%env(CODE_CHECKER_PORT)%'
  
  upload_directory: '%kernel.project_dir%/public/uploads/images'
    
